Improwised/improwised-new-website

newapp/src/content/blogs/ci-cd-in-air-gapped-environments.mdx
- Added 22nd blog - CI/CD in Air-Gapped Environments: Running Pipelines Without Internet Access
=> Newapp - 21st blog

newapp/src/components/PESection.astro, newapp/src/components/common/Accordion.svelte
- fixed service accordion behaviour in mobile view
=> Newapp - fixed service accordion behaviour

newapp/astro.config.mjs, newapp/src/components/AboutusSection.astro, newapp/src/components/CTASection.astro, newapp/src/components/CustomCard.astro, newapp/src/components/Footer.astro, newapp/src/components/Header.astro, newapp/src/components/HeroSection.astro, newapp/src/components/PlatformEngServiceSection.astro, newapp/src/components/Sidebar.astro, newapp/src/components/common/Accordion.svelte, newapp/src/components/common/BlogsCarousel.svelte, newapp/src/components/common/Dropdown.svelte, newapp/src/content/services/1-service.mdx, newapp/src/content/services/2-service.mdx, newapp/src/content/services/3-service.mdx, newapp/src/content/services/4-service.mdx, newapp/src/pages/blog/[...slug].astro, newapp/src/pages/blog/index.astro, newapp/src/pages/careers/index.astro, newapp/src/pages/services/[servicepage]/[block].astro, webapp/src/pages/careers/jobs/index.astro
=> fix: added trailing slashes

newapp/src/components/BaseHead.astro, newapp/src/content.config.ts, newapp/src/content/blogs/zero-downtime-architecture.mdx, newapp/src/pages/blog/[...slug].astro
- added blog's detail page seo content
=> fix: added blogs detail page seo content

newapp/src/components/AboutusSection.astro, newapp/src/components/CTASection.astro, newapp/src/components/EventSlider.astro, newapp/src/components/Footer.astro, newapp/src/components/common/Accordion.svelte, newapp/src/components/common/SectionTitle.svelte, newapp/src/components/ui/card/card-title.svelte, newapp/src/pages/about-improwised.astro, newapp/src/pages/careers/index.astro
=> fix: modified header tags

newapp/src/components/HeroSection.astro
- removed background-image class
=> fix: removed images from background-image class

newapp/src/content/teams/teams.mdx
=> feat: remove employee image

newapp/src/components/Footer.astro
- added instagram accout in footer
=> feat: added instagram account

newapp/src/content/blogs/cloud-computing-a-revolutionary-business-model-innovation.mdx, newapp/src/content/blogs/cloud-cost-optimization-maximizing-profit-and-scalability.mdx, newapp/src/content/blogs/embracing-open-tf-our-commitment-to-open-source-and-terraform.mdx, newapp/src/content/blogs/the-role-of-platform-engineering-in-multi-cloud-strategies-for-2025.mdx, newapp/src/content/blogs/the-role-of-tooling-and-infrastructure-in-measuring-dora-metrics.mdx, newapp/src/content/blogs/top-cloud-trends-to-watch-in-2025-implications-for-platform-engineers.mdx, newapp/src/pages/about-improwised.astro, newapp/src/styles/global.css
- Modified founder details on about us page
- Added nested links on blog details page
=> feat: modified about us page and added nested links on blog details page

newapp/README.md, newapp/tech.md
- Modified the README.md file by adding instructions for local development
=> fix: fixed readme

newapp/src/components/common/SidebarNav.svelte, newapp/src/content/blog/top-10-platform-engineering-companies.md, newapp/src/pages/blog/[...slug].astro, newapp/src/styles/global.css
- Modified the spacing and sizing for paragraph and headings for the blogs pages
=> fix: modify the spacing and sizing of the blogs pages

newapp/src/content/pages/terms-of-use/terms-of-use.md
- added refund policy in terms of service page
=> fix: added refund policy in terms of service page

newapp/src/content/blog/jenkins-to-gitops-github-fluxcd-devops-transformation.md, newapp/src/content/blog/top-golang-development-companies-2025.md, newapp/src/pages/blog/[...slug].astro, newapp/src/styles/global.css
- fixed styling and responsiveness of blogs pages
=> fix: styling of blogs

newapp/src/content.config.ts, newapp/src/content/careers/business-development-executive.mdx, newapp/src/content/careers/devops-engineer.mdx, newapp/src/content/careers/senior-software-engineer.mdx, newapp/src/content/careers/software-engineer.mdx, newapp/src/pages/careers/jobs/[...slug].astro
=> fix: removed job posting date

newapp/public/_redirects
- add redirect rule for redirecting blogs url to blog
=> feat: add redirect rule for cloudflare

newapp/src/images/tech/FullTechMobileNew.svg, newapp/src/images/tech/FullTechNew.svg
=> feat: update svg of tech result section

newapp/src/images/tech/FullTechMobileNew.svg, newapp/src/images/tech/FullTechNew.svg
Reverts Improwised/improwised-new-website#218
=> Revert "feat: update svg of tech result section"

newapp/src/content.config.ts, newapp/src/content/blog/platform-engineering-vs-devops.md, newapp/src/pages/blog/[...slug].astro
- added faqs and fixed sidebar for platform vs devops blog
=> fix: added faqs and fixed sidebar for platform vs devops blog

newapp/src/layouts/Layout.astro
- fixed the refreshing issue related to dark and light mode
=> fix: modified switching of dark and light mode

newapp/src/content/blog/cloud-cost-optimization-maximizing-profit-and-scalability.md, newapp/src/content/blog/kubernetes-base-not-goal.md, newapp/src/content/blog/what-platform-engineers-need-to-know-about-the-most-important-cloud-trends.md
=> fix; replaced blog urls

newapp/src/components/JsonFaqs.astro, newapp/src/layouts/Layout.astro, newapp/src/pages/blog/[...slug].astro
-  added json LD schema for faqs
=> feat: added json LD schema for faqs
